# override_output_path: eval_results_20240520_044025

endpoints:
  - "http://localhost:5001/predict"

batch_size: 20
openai_azure_deployment: "gpt-35-turbo-1106"
num_openai_workers: 5

video_path: "/data/msrvtt-qa/videos"
qa_path: "/data/msrvtt-qa/qa.json"

temperature: 0.1
max_new_tokens: 1024
